owner: InfraIT-Concordia
repo: status-page
sites:
  # Sitios Web
  - name: Portal Municipal Concordia
    url: https://concordia.gob.ar
    method: GET
    maxResponseTime: 4000
    group: Sitios Web

  - name: Recursos Humanos (RRHH)
    url: https://rrhh.concordia.gob.ar
    method: GET
    maxResponseTime: 4000
    group: Sitios Web

  - name: Nube Concordia
    url: https://nube.concordia.ar
    method: GET
    maxResponseTime: 5000
    group: Sitios Web

  # Servidor SOS
  - name: SOS - Sitio Web
    url: https://sos.concordia.gob.ar
    method: GET
    group: Servidor SOS

  - name: SOS - HTTPS (443)
    url: tcp-ping://172.16.0.51:443
    group: Servidor SOS
    secret: true

  - name: SOS - HTTP (80)
    url: tcp-ping://172.16.0.51:80
    group: Servidor SOS
    secret: true

status-website:
  cname: status2.concordia.gob.ar
  logoUrl: https://concordia.gob.ar/sites/default/files/logo-municipalidad-concordia.png
  name: Monitoreo Concordia
  introTitle: "Panel de Estado de Servicios - Concordia"
  introMessage: Monitoreo en tiempo real de la infraestructura web de la ciudad.
  navbar:
    - title: Estado
      href: /
    - title: GitHub
      href: https://github.com/InfraIT-Concordia/status-page

  i18n:
    activeStatus: Estado en vivo
    allSystemsOperational: Todos los sistemas funcionan correctamente
    degradedPerformance: Rendimiento degradado
    majorOutage: Caída total del servicio
    partialOutage: Caída parcial
    incidentHistory: Historial de incidentes
    overallPageStatus: Estado general del panel
    uptime: Tiempo de actividad
    averageResponseTime: Tiempo medio de respuesta
    responseTimeGraphAlt: Gráfico de tiempo de respuesta
    liveStatus: Estado actual
    all: Todo
    day: Día
    month: Mes
    year: Año
    overallUptime: Tiempo de actividad total
    overallUptimePublic: Tiempo de actividad (público)
    status: Estado
    history: Historial
    ms: ms
    loading: Cargando...
    up: En línea
    down: Caído
    degraded: Degradado
